services:
  - type: web_service
    name: portfolio
    env: node
    plan: free
    packageManager: npm
    buildCommand: npm install --include=dev && ./node_modules/.bin/vite build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
