services:
  - type: web_service
    name: portfolio
    env: node
    plan: free
    packageManager: npm
    installCommand: npm install
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
